config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "pages#about", as: :about
  get "contact" => "pages#contact_us", as: :contact
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <%= link_to "Inicio", root_path %>
    <%= link_to "Nosotros", about_path %>
    <%= link_to "Contacto", contact_path %>
    <%= yield %>
</html>

app/views/pages/about.html.erb
<!-- FILEPATH: /home/armindroid/Workspace/internMe-web/app/views/pages/about.html.erb -->
<p>Bienvenido a nuestra página InternMe. Aquí puedes encontrar información sobre el gran equipo detras de estre proyecto.</p>

app/views/pages/contact_us.html.erb
<!-- FILEPATH: /home/armindroid/Workspace/internMe-web/app/views/pages/contact_us.html.erb -->
<div class="page-header">
<h1>Contactanos</h1>

<form action="/contact" method="POST">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>

    <label for="message">Message:</label>
    <textarea id="message" name="message" required></textarea>

    <button type="submit">Submit</button>
</form>

app/views/pages/home.html.erb
<div class="page-header">
  <h1>InternMe</h1>
</div>
<h2>Bienvenido a InternMe</h2>
<p>Un lugar para encontrar paz y felicidad en el proceso</p>